site_name: Oxipay Documentation
pages:
- Home: index.md
- Platforms:
   - Shopify: platforms/shopify.md
   - WooCommerce: platforms/woocommerce.md
   - Magento 1: platforms/magento_1.md
   - Magento 2: platforms/magento_2.md
   - OneStep: platforms/onestep.md

- Custom Integration:
   - How it works: custom-integration/how-it-works.md
   - Gateway Signing Mechanism: custom-integration/gateway-signing-mechanism.md
   - API reference:
      - Request values: custom-integration/api-reference/request-values.md
      - Response values: custom-integration/api-reference/response-values.md
- Marketing & Advertising:
      - Introduction: guidelines/banner-adverts.md
      - Installing the Simple Way: guidelines/installing-simple.md
      - Installing the Complex Way: guidelines/installing-complex.md
      - Banners and Tags list: guidelines/banners.md
theme: flatly
extra_css: 
- css/styles.css