site_name: Oxipay Documentation
pages:

- Home: index.md

- Platforms:
   - Shopify: platforms/shopify.md
   - WooCommerce: platforms/woocommerce.md
   - Magento 1: platforms/magento_1.md
   - Magento 2: platforms/magento_2.md
   - OneStep: platforms/onestep.md

- Developer Resources:
   - Introduction: developer_resources/introduction.md
   - Checkout Process: developer_resources/checkout_process.md
   - API Reference: developer_resources/api_reference.md
   - Sample cURL Script: developer_resources/sample_curl.md
   - Signature Generation: developer_resources/signature_generation.md

- Marketing & Advertising:
      - Introduction: guidelines/banner-adverts.md
      - Banners and Tags list: guidelines/banners.md

theme: readthedocs
extra_css: [css/jquery.modal.min.css, css/custom.css]
