site_name: Oxipay Documentation
pages:
- Home: index.md
- Platforms:
   - Shopify: platforms/shopify.md
   - WooCommerce: platforms/woocommerce.md
   - Magento 1: platforms/magento_1.md
   - Magento 2: platforms/magento_2.md
   - OneStep: platforms/onestep.md

- Developer Resources:
   - Introduction: developer-resources/Introduction.md
   - API Reference: developer-resources/api-reference.md
   - Gateway Signing Mechanism: developer-resources/gateway-signing-mechanism.md
- Marketing & Advertising:
      - Introduction: guidelines/banner-adverts.md
      - Installing the Simple Way: guidelines/installing-simple.md
      - Installing the Complex Way: guidelines/installing-complex.md
      - Banners and Tags list: guidelines/banners.md
theme: flatly
extra_css: 
- css/styles.css